version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    container_name: app
    expose:
      - 8000
    ports:
      - 0.0.0.0:8000:8000
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres
    container_name: postgres
    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
        - .env
    networks:
      - default

networks:
  default:
